import 'package:customer_app/Screens/Store%20products%20screen/demoModal.dart';

List<MyCategories> democategoryList = [
  MyCategories(
    categoryName: 'Fruits and vegitables',
    imageUrl: 'assets/images/pineapple.png',
    products: [
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 Items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Blue Apple',
        quantity: '1000 Items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 Items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'White Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 Items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Blue Apple',
        quantity: '1000 Items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 Items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'White Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 Items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Blue Apple',
        quantity: '1000 Items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 Items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'White Apple',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Mango',
        imageUrl: 'assets/images/mango.png',

    products: [
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/mango.png',
        price: '40',
        productName: 'Sandwich Bread',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        price: '60',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Wheat bread',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    imageUrl: 'assets/images/apple.png',
    categoryName: 'Apple',
    products: [
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/apple.png',
        price: '90',
        productName: 'Milk',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '190',
        productName: 'Butter',
        quantity: '1000 Items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '103',
        productName: 'Cheese',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
        imageUrl: 'assets/images/orange.png',
    categoryName: 'ORANGE',
    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Blue Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'White Apple',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        quantity: '1000 items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Fruits and vegitables',
    imageUrl: 'assets/images/pineapple.png',
    products: [
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Red Apple',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Blue Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'White Apple',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Mango',
        imageUrl: 'assets/images/mango.png',

    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        price: '40',
        productName: 'Sandwich Bread',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        price: '60',
        productName: 'Wheat bread',
        quantity: '1000 Items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
    ],
  ),
  MyCategories(
    imageUrl: 'assets/images/apple.png',
    categoryName: 'Apple',
    products: [
      Products(
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        price: '90',
        productName: 'Milk',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/apple.png',
        price: '190',
        productName: 'Butter',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/apple.png',
        price: '103',
        productName: 'Cheese',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
        imageUrl: 'assets/images/orange.png',
    categoryName: 'ORANGE',
    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Blue Apple',
        quantity: '1000 items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        price: '10',
        productName: 'White Apple',
        quantity: '1000 items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Fruits and vegitables',
    imageUrl: 'assets/images/pineapple.png',
    products: [
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Red Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Blue Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Golden Apple',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'White Apple',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Mango',
        imageUrl: 'assets/images/mango.png',

    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        price: '40',
        productName: 'Sandwich Bread',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        price: '60',
        productName: 'Wheat bread',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    imageUrl: 'assets/images/apple.png',
    categoryName: 'Apple',
    products: [
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/apple.png',
        price: '90',
        productName: 'Milk',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '190',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Butter',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '103',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Cheese',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
        imageUrl: 'assets/images/orange.png',
    categoryName: 'ORANGE',
    products: [
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Red Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Blue Apple',
        quantity: '1000 items',
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'White Apple',
        quantity: '1000 items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Fruits and vegitables',
    imageUrl: 'assets/images/pineapple.png',
    products: [
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        productName: 'Blue Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/pineapple.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'White Apple',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    categoryName: 'Mango',
        imageUrl: 'assets/images/mango.png',

    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        price: '40',
        productName: 'Sandwich Bread',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/mango.png',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        price: '60',
        productName: 'Wheat bread',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
    imageUrl: 'assets/images/apple.png',
    categoryName: 'Apple',
    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '90',
        productName: 'Milk',
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '190',
        productName: 'Butter',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        quantity: '1000 Items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/apple.png',
        price: '103',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'Cheese',
        quantity: '1000 Items',
      ),
    ],
  ),
  MyCategories(
        imageUrl: 'assets/images/orange.png',
    categoryName: 'ORANGE',
    products: [
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Red Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Blue Apple',
        quantity: '1000 items',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
      ),
      Products(
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        productName: 'Golden Apple',
        quantity: '1000 items',
      ),
      Products(
        productId: 1,
        imageLocation: 'assets/images/orange.png',
        price: '10',
        varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
        productName: 'White Apple',
        quantity: '1000 items',
      ),
    ],
  ),
  // MyCategories(
  //       imageUrl: 'assets/images/orange2.png',
  //   categoryName: 'Bakery',
  //   products: [
  //     Products(
  //       productId: 1,
        // varients: [Varients(price: '10',unit: '10 g'),Varients(price: '20',unit: '20 g'),],
  //       imageLocation: 'assets/images/orange2.png',
  //       price: '40',
  //       productName: 'Sandwich Bread',
  //       quantity: '1000 Items',
  //     ),
  //     Products(
  //       productId: 1,
  //       imageLocation: 'assets/images/orange2.png',
  //       price: '60',
  //       productName: 'Wheat bread',
  //       quantity: '1000 Items',
  //     ),
  //   ],
  // ),
  // MyCategories(
  //   imageUrl: 'assets/images/Frame-2.png',
  //   categoryName: 'Dairy',
  //   products: [
  //     Products(
  //       productId: 1,
  //       imageLocation: 'assets/images/dairy.jpg',
  //       price: '90',
  //       productName: 'Milk',
  //       quantity: '1000 Items',
  //     ),
  //     Products(
  //       productId: 1,
  //       imageLocation: 'assets/images/dairy.jpg',
  //       price: '190',
  //       productName: 'Butter',
  //       quantity: '1000 Items',
  //     ),
  //     Products(
  //       productId: 1,
  //       imageLocation: 'assets/images/dairy.jpg',
  //       price: '103',
  //       productName: 'Cheese',
  //       quantity: '1000 Items',
  //     ),
  //   ],
  // ),
];
